language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pylint entities.py fakes.py fileresultsink.py main.py objdetector.py service.py videocapture.py webservice.py
